In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 1 
Consider the Finnish life table. Suppose infant mortality $q(0)$ is halved while other age-
specific mortality rates are unchanged. What is the effect on the life expectancy at birth
$e_0$ ?

In [3]:
df_fin = pd.read_excel('/home/oscar/repos/StochasticDemography/data/finland2015.xlsx')
df_fin.head(5)
df_fin.tail(5)

year age x     m(x)     q(x)  a(x)    l(x)  d(x)   L(x)     T(x)   e(x)
0  2015     0  0.00168  0.00168  0.15  100000   168  99856  8143956  81.44
1  2015     1  0.00009  0.00009  0.50   99832     9  99828  8044099  80.58
2  2015     2  0.00013  0.00013  0.50   99823    13  99817  7944272  79.58
3  2015     3  0.00008  0.00008  0.50   99810     8  99806  7844455  78.59
4  2015     4  0.00006  0.00006  0.50   99802     6  99799  7744649  77.60

year age x     m(x)     q(x)  a(x)  l(x)  d(x)  L(x)  T(x)  e(x)
106  2015   106  0.68827  0.51205  0.50    50    26    38    71  1.40
107  2015   107  0.72078  0.52983  0.50    25    13    18    33  1.35
108  2015   108  0.75118  0.54608  0.50    12     6     8    15  1.30
109  2015   109  0.77932  0.56080  0.50     5     3     4     7  1.27
110  2015  110+  0.80513  1.00000  1.24     2     2     3     3  1.24

A new $l_2(x)$ column is calculated from the formula:

$$l_2(0) = 100000$$

$$l_2(x+1) = (1 - q_2(x))l_2(x), \quad \textrm{ when }x>0$$

the exptected value is calculated from the formula 

$$e_0 = \frac{1}{l_0}\sum_{y=1}^{\infty} l_y + \frac{1}{2}$$
    


In [4]:
# Adding a new mortality rate 'q2(x)'
df_fin['q2(x)'] = df_fin['q(x)']
df_fin.loc[0, 'q2(x)'] /=2


# Calculating new l(x) values 
cur_l = 10**5
new_lx = [cur_l]

for q in df_fin['q2(x)'][:-1]:
    cur_l *= (1 - q)
    new_lx.append(np.round(cur_l))

df_fin['l2(x)'] = pd.Series(new_lx)
df_fin.head(10)
df_fin.tail(10)

def calc_e(ages, n):
    denominator = ages[n]
    nominator = np.sum(ages[n+1:])
    return nominator / denominator + 0.5

age = 0
e0_new = calc_e(df_fin['l2(x)'], age)
e0_old = calc_e(df_fin['l(x)'], age)

print("New expected life time at age {0}: {1}".format(age, e0_new))

print("Old expected life time at age {0}: {1}".format(age, e0_old))

year age x     m(x)     q(x)  a(x)    l(x)  d(x)   L(x)     T(x)   e(x)  \
0  2015     0  0.00168  0.00168  0.15  100000   168  99856  8143956  81.44   
1  2015     1  0.00009  0.00009  0.50   99832     9  99828  8044099  80.58   
2  2015     2  0.00013  0.00013  0.50   99823    13  99817  7944272  79.58   
3  2015     3  0.00008  0.00008  0.50   99810     8  99806  7844455  78.59   
4  2015     4  0.00006  0.00006  0.50   99802     6  99799  7744649  77.60   
5  2015     5  0.00008  0.00008  0.50   99795     8  99791  7644850  76.61   
6  2015     6  0.00002  0.00002  0.50   99787     2  99787  7545059  75.61   
7  2015     7  0.00005  0.00005  0.50   99786     5  99783  7445272  74.61   
8  2015     8  0.00003  0.00003  0.50   99781     3  99779  7345489  73.62   
9  2015     9  0.00008  0.00008  0.50   99778     8  99773  7245710  72.62   

     q2(x)     l2(x)  
0  0.00084  100000.0  
1  0.00009   99916.0  
2  0.00013   99907.0  
3  0.00008   99894.0  
4  0.00006   99886.0  
5  0.00008   99880.0  
6  0.00002   99872.0  
7  0.00005   99870.0  
8  0.00003   99865.0  
9  0.00008   99862.0

year age x     m(x)     q(x)  a(x)  l(x)  d(x)  L(x)  T(x)  e(x)  \
101  2015   101  0.50394  0.40252  0.50  1000   403   799  1824  1.82   
102  2015   102  0.54245  0.42671  0.50   598   255   470  1025  1.72   
103  2015   103  0.58056  0.44995  0.50   343   154   266   555  1.62   
104  2015   104  0.61784  0.47202  0.50   188    89   144   290  1.54   
105  2015   105  0.65386  0.49276  0.50   100    49    75   146  1.46   
106  2015   106  0.68827  0.51205  0.50    50    26    38    71  1.40   
107  2015   107  0.72078  0.52983  0.50    25    13    18    33  1.35   
108  2015   108  0.75118  0.54608  0.50    12     6     8    15  1.30   
109  2015   109  0.77932  0.56080  0.50     5     3     4     7  1.27   
110  2015  110+  0.80513  1.00000  1.24     2     2     3     3  1.24   

       q2(x)   l2(x)  
101  0.40252  1001.0  
102  0.42671   598.0  
103  0.44995   343.0  
104  0.47202   189.0  
105  0.49276   100.0  
106  0.51205    51.0  
107  0.52983    25.0  
108  0.54608    12.0  
109  0.56080     5.0  
110  1.00000     2.0

New expected life time at age 0: 81.50798
Old expected life time at age 0: 81.44012


## 4

A grandmother, aged 55, pledges to pay her 5-year-old grandson a yearly sum of 500
e. The payments are to be continued until the death of either of them. What is the
expected present value of this pledge, assuming (1) that the life times of both persons are
independent random variables and (2) that the interest rate ρ = 0.02 is constant. Use a
fairly recent life table.


Let $A_g$, $A_s$ be the ages of grandmother and grandson.

$T = min(A_g, A_s)$

$P(T > t) = P(min(A_g, A_s) > t) = P(A_g > t, A_s > t) = P(A_g > t)P(A_s > t)$

let $I(x)$ be one if $T>x$ and zero otherwise.

$T = \int_{0}^{\infty} I(t) dt$

$E(I(x)) = l^{(g)}(x) l^{(s)}(x)$

The present value of the payments $C$ in the continuous case would be 

$$C = \int_{0}^{\infty} 500e^{-0.02t} I(t)dt = 500\int_{0}^{\infty} e^{-0.02t} l^{(g)}(t)l^{(s)}(t)dt$$

The grandmother has at most 56 years left. Assuming the first payment is paid right now the expected value $C$ of the payments is 

$$C = 500\sum_{k=0}^{55} (\frac{1}{1 + 0.02})^{k} l_{55+k}^{(g)} l_{5+k}^{(s)}, 
\quad \textrm{where} \quad
l^{(g)} = \frac{l_{x}}{l_{55}} \quad \textrm{and} \quad l^{(s)} = \frac{l_{x}}{l_5}$$


In [5]:
def calc_expected_value(df, age_g, age_s, rate):

    l_g = df.loc[age_g:, 'l(x)'].values / df.loc[age_g, 'l(x)']
    l_s = df.loc[age_s: len(l_g) + age_s - 1, 'l(x)'].values / df.loc[age_s, 'l(x)']

    disc_factor = 1 / (1 + rate)
    l_gs = l_g * l_s

    print(len(l_g), len(l_s))

    C = 0
    
    k = 0
    for val in l_gs:
        C += disc_factor ** k * val
        k += 1

    C *= 500
    return C


r = 0.02
C = calc_expected_value(df_fin, 55, 5, r)

print("Exptected value of payments: ", np.round(C, decimals=4))



56 56
Exptected value of payments:  10789.1003


In [30]:
# check with A_g = 110
C110 = calc_expected_value(df_fin, 110, 5, r)

print("Exptected value of payments: ", np.round(C110, decimals=4))

1 1
Exptected value of payments:  500.0


## 10

find $(I - A)^{-1}m$

In [6]:
A = np.zeros([8,8])

low = np.arange(7)
A[low+1, low] = np.array([0.99, 0.97, 0.9, 0.8, 0.7, 0.5, 0.3])
A[0, :] = np.array([0, 0, 0.35, 0.5, 0.2, 0.05, 0, 0])

print('A =\n', A, '\n')
print('I - A =\n', np.eye(8) - A, '\n')

I = np.linalg.inv(np.eye(8) - A)
print('Inverse = \n',np.round(I, decimals=3), '\n')

m = 0.01 * np.ones([8,1])
print('m =\n', m, '\n')

Im = I.dot(m)
print('Answer =\n',Im)

A =
 [[0.   0.   0.35 0.5  0.2  0.05 0.   0.  ]
 [0.99 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.97 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.9  0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.8  0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.7  0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.5  0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.3  0.  ]] 

I - A =
 [[ 1.    0.   -0.35 -0.5  -0.2  -0.05  0.    0.  ]
 [-0.99  1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.   -0.97  1.    0.    0.    0.    0.    0.  ]
 [ 0.    0.   -0.9   1.    0.    0.    0.    0.  ]
 [ 0.    0.    0.   -0.8   1.    0.    0.    0.  ]
 [ 0.    0.    0.    0.   -0.7   1.    0.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.5   1.    0.  ]
 [ 0.    0.    0.    0.    0.    0.   -0.3   1.  ]] 

Inverse = 
 [[14.435 13.57  13.99   9.931  3.392  0.722  0.     0.   ]
 [14.29  14.435 13.85   9.832  3.358  0.715  0.     0.   ]
 [13.862 14.002 14.435  9.537  3.257  0.693 -0.    -0.   ]
 [12.476 12.602 12.991  9.583  2.932  0

In [13]:
np.round(I.dot(np.eye(8) - A), decimals=10)

array([[ 1.,  0.,  0.,  0.,  0., -0.,  0.,  0.],
       [-0.,  1.,  0., -0.,  0., -0.,  0.,  0.],
       [-0.,  0.,  1., -0.,  0., -0.,  0.,  0.],
       [-0.,  0.,  0.,  1.,  0., -0.,  0.,  0.],
       [ 0.,  0.,  0., -0.,  1., -0.,  0.,  0.],
       [-0.,  0.,  0., -0.,  0.,  1.,  0.,  0.],
       [-0.,  0.,  0., -0.,  0., -0.,  1.,  0.],
       [-0.,  0.,  0.,  0.,  0., -0.,  0.,  1.]])

In [25]:
n = np.ones([8,1])
np.linalg.matrix_power(A, 1).dot(n) + m

array([[1.11],
       [1.  ],
       [0.98],
       [0.91],
       [0.81],
       [0.71],
       [0.51],
       [0.31]])

In [20]:
l_g = df_fin.loc[55:, 'l(x)'].values / 10**5
l_s = df_fin.loc[5: len(l_g) + 4, 'l(x)'].values / 10**5

print(len(l_g), len(l_s))

r = 1 / (1 + 0.02)
l_gs = l_g * l_s

C = 0
k = 0

for val in l_gs:
    C += r ** k * val
    k += 1

C *= 500

print("Exptected value of payments: ", np.round(C, decimals=4))

56 56
Exptected value of payments:  10256.52


In [11]:
df_fin.head()

year age x     m(x)     q(x)  a(x)    l(x)  d(x)   L(x)     T(x)   e(x)
0  2015     0  0.00168  0.00168  0.15  100000   168  99856  8143956  81.44
1  2015     1  0.00009  0.00009  0.50   99832     9  99828  8044099  80.58
2  2015     2  0.00013  0.00013  0.50   99823    13  99817  7944272  79.58
3  2015     3  0.00008  0.00008  0.50   99810     8  99806  7844455  78.59
4  2015     4  0.00006  0.00006  0.50   99802     6  99799  7744649  77.60

In [12]:
df_fin.tail(5)

year age x     m(x)     q(x)  a(x)  l(x)  d(x)  L(x)  T(x)  e(x)
106  2015   106  0.68827  0.51205  0.50    50    26    38    71  1.40
107  2015   107  0.72078  0.52983  0.50    25    13    18    33  1.35
108  2015   108  0.75118  0.54608  0.50    12     6     8    15  1.30
109  2015   109  0.77932  0.56080  0.50     5     3     4     7  1.27
110  2015  110+  0.80513  1.00000  1.24     2     2     3     3  1.24

In [5]:
A = np.zeros([8,8])

low = np.arange(7)
A[low+1, low] = np.array([0.99, 0.97, 0.9, 0.8, 0.7, 0.5, 0.3])
A[0, :] = np.array([0, 0, 0.35, 0.5, 0.2, 0.05, 0, 0])

n = np.ones((8,1))

print(A.dot(n))
print(np.sum(A.dot(n)))

[[1.1 ]
 [0.99]
 [0.97]
 [0.9 ]
 [0.8 ]
 [0.7 ]
 [0.5 ]
 [0.3 ]]
6.26


In [6]:
ANW = A[:6, :6]
np.linalg.matrix_power(ANW, 9)

array([[0.17374984, 0.18837134, 0.25184872, 0.19016633, 0.06610619,
        0.0139848 ],
       [0.27689905, 0.17374984, 0.19225528, 0.16935063, 0.06226893,
        0.01437903],
       [0.2789532 , 0.27130513, 0.17374984, 0.09872667, 0.03099189,
        0.00658603],
       [0.11854857, 0.25359381, 0.25172641, 0.12764761, 0.03697465,
        0.0059757 ],
       [0.09561122, 0.09579683, 0.20914954, 0.18657467, 0.0678906 ,
        0.01493925],
       [0.20914954, 0.06760389, 0.06913173, 0.08133593, 0.03253437,
        0.00813359]])

Right eigenvector

In [60]:
eig_val, eig_vect = np.linalg.eig(A)
max_eigenvalue, i = np.max(np.abs(eig_val)), np.argmax(np.abs(eig_val))
print(max_eigenvalue.round(decimals=4), i)
print(eig_vect[:,i] / eig_vect[0,i])

0.9815 2
[1.        -0.j 1.00865913-0.j 0.99683984-0.j 0.9140651 -0.j
 0.74503443-0.j 0.53135358-0.j 0.27068416-0.j 0.08273577-0.j]


Left eigenvector

In [61]:
eig_val, eig_vect = np.linalg.eig(A.T)
max_eigenvalue, i = np.max(np.abs(eig_val)), np.argmax(np.abs(eig_val))
print(max_eigenvalue.round(decimals=4), i)
print(eig_vect[:,i] / eig_vect[0,i])

0.9815 0
[ 1.        -0.j  0.99141521-0.j  1.00317018-0.j  0.7051251 -0.j
  0.24010129-0.j  0.05094238-0.j -0.        -0.j -0.        -0.j]


Since $\lambda < 1, A^t n$ goes to zero as t goes to infinity

In [64]:
np.linalg.matrix_power(A, 40000).dot(np.ones(8))

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
w = np.array([1, 1.0087, 0.9968, 0.9141, 0.7450, 0.5314, 0.2707, 0.0827])
w3 = A.dot(w)
w3

array([0.9815  , 0.99    , 0.978439, 0.89712 , 0.73128 , 0.5215  ,
       0.2657  , 0.08121 ])

In [82]:
m = 0.01 * np.ones(8).reshape(-1,1)
m

array([[0.01],
       [0.01],
       [0.01],
       [0.01],
       [0.01],
       [0.01],
       [0.01],
       [0.01]])

array([[0.56040397],
       [0.56479993],
       [0.55785593],
       [0.51207034],
       [0.41965627],
       [0.30375939],
       [0.16187969],
       [0.05856391]])