In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 1 
Consider the Finnish life table. Suppose infant mortality $q(0)$ is halved while other age-
specific mortality rates are unchanged. What is the effect on the life expectancy at birth
$e_0$ ?

In [2]:
df_fin = pd.read_excel('/home/oscar/repos/StochasticDemography/data/finland2015.xlsx')
df_fin.head(5)
df_fin.tail(5)

year age x     m(x)     q(x)  a(x)    l(x)  d(x)   L(x)     T(x)   e(x)
0  2015     0  0.00168  0.00168  0.15  100000   168  99856  8143956  81.44
1  2015     1  0.00009  0.00009  0.50   99832     9  99828  8044099  80.58
2  2015     2  0.00013  0.00013  0.50   99823    13  99817  7944272  79.58
3  2015     3  0.00008  0.00008  0.50   99810     8  99806  7844455  78.59
4  2015     4  0.00006  0.00006  0.50   99802     6  99799  7744649  77.60

year age x     m(x)     q(x)  a(x)  l(x)  d(x)  L(x)  T(x)  e(x)
106  2015   106  0.68827  0.51205  0.50    50    26    38    71  1.40
107  2015   107  0.72078  0.52983  0.50    25    13    18    33  1.35
108  2015   108  0.75118  0.54608  0.50    12     6     8    15  1.30
109  2015   109  0.77932  0.56080  0.50     5     3     4     7  1.27
110  2015  110+  0.80513  1.00000  1.24     2     2     3     3  1.24

A new $l_2(x)$ column is calculated from the formula:

$$l_2(0) = 100000$$

$$l_2(x+1) = (1 - q_2(x))l_2(x), \quad \textrm{ when }x>0$$

the exptected value is calculated from the formula 

$$e_0 = \frac{1}{l_0}\sum_{y=1}^{\infty} l_y + \frac{1}{2}$$
    


In [29]:
# Adding a new mortality rate 'q2(x)'
df_fin['q2(x)'] = df_fin['q(x)']
df_fin.loc[0, 'q2(x)'] /=2


# Calculating new l(x) values 
cur_l = 10**5
new_lx = [cur_l]

for q in df_fin['q2(x)'][:-1]:
    cur_l *= (1 - q)
    new_lx.append(np.round(cur_l))

df_fin['l2(x)'] = pd.Series(new_lx)
#df_fin.head(10)
df_fin#.tail(10)

def calc_e(ages, n):
    denominator = ages[n]
    nominator = np.sum(ages[n+1:])
    return nominator / denominator + 0.5

age = 0
e0_new = calc_e(df_fin['l2(x)'], age)
e0_old = calc_e(df_fin['l(x)'], age)

print("New expected life time at age {0}: {1}".format(age, e0_new))

print("Old expected life time at age {0}: {1}".format(age, e0_old))

year age x     m(x)     q(x)  a(x)    l(x)  d(x)   L(x)     T(x)   e(x)  \
0    2015     0  0.00168  0.00168  0.15  100000   168  99856  8143956  81.44   
1    2015     1  0.00009  0.00009  0.50   99832     9  99828  8044099  80.58   
2    2015     2  0.00013  0.00013  0.50   99823    13  99817  7944272  79.58   
3    2015     3  0.00008  0.00008  0.50   99810     8  99806  7844455  78.59   
4    2015     4  0.00006  0.00006  0.50   99802     6  99799  7744649  77.60   
5    2015     5  0.00008  0.00008  0.50   99795     8  99791  7644850  76.61   
6    2015     6  0.00002  0.00002  0.50   99787     2  99787  7545059  75.61   
7    2015     7  0.00005  0.00005  0.50   99786     5  99783  7445272  74.61   
8    2015     8  0.00003  0.00003  0.50   99781     3  99779  7345489  73.62   
9    2015     9  0.00008  0.00008  0.50   99778     8  99773  7245710  72.62   
10   2015    10  0.00005  0.00005  0.50   99769     5  99767  7145936  71.62   
11   2015    11  0.00017  0.00017  0.50   99764    17  99756  7046169  70.63   
12   2015    12  0.00009  0.00009  0.50   99748     9  99743  6946413  69.64   
13   2015    13  0.00014  0.00014  0.50   99739    14  99732  6846670  68.65   
14   2015    14  0.00005  0.00005  0.50   99725     5  99722  6746938  67.66   
15   2015    15  0.00017  0.00017  0.50   99720    17  99711  6647216  66.66   
16   2015    16  0.00019  0.00019  0.50   99703    19  99694  6547504  65.67   
17   2015    17  0.00020  0.00020  0.50   99684    20  99674  6447811  64.68   
18   2015    18  0.00029  0.00029  0.50   99664    29  99650  6348136  63.70   
19   2015    19  0.00049  0.00049  0.50   99635    49  99611  6248486  62.71   
20   2015    20  0.00041  0.00041  0.50   99587    40  99567  6148875  61.74   
21   2015    21  0.00050  0.00050  0.50   99547    49  99522  6049308  60.77   
22   2015    22  0.00055  0.00055  0.50   99497    55  99470  5949786  59.80   
23   2015    23  0.00039  0.00039  0.50   99442    39  99423  5850317  58.83   
24   2015    24  0.00055  0.00055  0.50   99404    54  99377  5750894  57.85   
25   2015    25  0.00055  0.00054  0.50   99349    54  99322  5651517  56.89   
26   2015    26  0.00054  0.00054  0.50   99295    54  99269  5552195  55.92   
27   2015    27  0.00041  0.00041  0.50   99242    41  99221  5452926  54.95   
28   2015    28  0.00050  0.00050  0.50   99201    49  99176  5353705  53.97   
29   2015    29  0.00064  0.00064  0.50   99152    64  99120  5254529  52.99   
..    ...   ...      ...      ...   ...     ...   ...    ...      ...    ...   
81   2015    81  0.04821  0.04707  0.50   62202  2928  60738   531344   8.54   
82   2015    82  0.05662  0.05506  0.50   59274  3264  57642   470606   7.94   
83   2015    83  0.06615  0.06403  0.50   56010  3586  54217   412965   7.37   
84   2015    84  0.07390  0.07127  0.50   52424  3736  50556   358748   6.84   
85   2015    85  0.08728  0.08363  0.50   48687  4072  46652   308192   6.33   
86   2015    86  0.10415  0.09899  0.50   44616  4417  42407   261541   5.86   
87   2015    87  0.10998  0.10425  0.50   40199  4191  38104   219133   5.45   
88   2015    88  0.12381  0.11660  0.50   36008  4198  33909   181030   5.03   
89   2015    89  0.14446  0.13473  0.50   31810  4286  29667   147121   4.63   
90   2015    90  0.16550  0.15285  0.50   27524  4207  25421   117454   4.27   
91   2015    91  0.18111  0.16607  0.50   23317  3872  21381    92033   3.95   
92   2015    92  0.19817  0.18030  0.50   19445  3506  17692    70652   3.63   
93   2015    93  0.23800  0.21269  0.50   15939  3390  14244    52961   3.32   
94   2015    94  0.24937  0.22172  0.50   12549  2782  11158    38717   3.09   
95   2015    95  0.28927  0.25272  0.50    9766  2468   8532    27559   2.82   
96   2015    96  0.32124  0.27678  0.50    7298  2020   6288    19027   2.61   
97   2015    97  0.35513  0.30158  0.50    5278  1592   4482    12739   2.41   
98   2015    98  0.39070  0.32685  0.50    3686  1205   3084     8257   2.24   
99   

New expected life time at age 0: 81.50798
Old expected life time at age 0: 81.44012


## 4

A grandmother, aged 55, pledges to pay her 5-year-old grandson a yearly sum of 500
e. The payments are to be continued until the death of either of them. What is the
expected present value of this pledge, assuming (1) that the life times of both persons are
independent random variables and (2) that the interest rate ρ = 0.02 is constant. Use a
fairly recent life table.


Let $A_g$, $A_s$ be the ages of grandmother and grandson.

$T = min(A_g, A_s)$

$P(T > t) = P(min(A_g, A_s) > t) = P(A_g > t, A_s > t) = P(A_g > t)P(A_s > t)$

let $I(x)$ be one if $T>x$ and zero otherwise.

$T = \int_{0}^{\infty} I(t) dt$

$E(I(x)) = l^{(g)}(x) l^{(s)}(x)$

The present value of the payments $C$ in the continuous case would be 

$$C = \int_{0}^{\infty} 500e^{-0.02t} I(t)dt = 500\int_{0}^{\infty} e^{-0.02t} l^{(g)}(t)l^{(s)}(t)dt$$

The grandmother has at most 56 years left. Assuming the first payment is paid right now the expected value $C$ of the payments is 

$$C = 500\sum_{k=0}^{55} (\frac{1}{1 + 0.02})^{k} l_{55+k}^{(g)} l_{5+k}^{(s)}, 
\quad \textrm{where} \quad
l^{(g)} = \frac{l_{x}}{l_{55}} \quad \textrm{and} \quad l^{(s)} = \frac{l_{x}}{l_5}$$


In [106]:
def calc_expected_value(df_male, df_female, age_g, age_s, rate):

    l_g = df_female.loc[age_g:, 'l(x)'].values / df_female.loc[age_g, 'l(x)']
    
    l_s = df_male.loc[age_s: len(l_g) + age_s - 1, 'l(x)'].values / df_male.loc[age_s, 'l(x)']

    disc_factor = 1 / (1 + rate)
    l_gs = l_g * l_s

    print(len(l_g), len(l_s))

    C = 0
    
    k = 0
    for val in l_gs:
        C += disc_factor ** k * val
        k += 1

    C *= 500
    return C


r = 0.02
C = calc_expected_value(df_male, df_female, 55, 5, r)

print("Exptected value of payments: ", np.round(C, decimals=4))



56 56
Exptected value of payments:  11410.5345


In [31]:
# check with A_g = 110
C110 = calc_expected_value(df_fin, 110, 5, r)

print("Exptected value of payments: ", np.round(C110, decimals=4))

1 1
Exptected value of payments:  500.0


In [86]:
df = pd.read_excel('life_table_fin2015_male_female.xlsx')
df = df.iloc[:, :10]

In [104]:
df_male = df.iloc[250:362,:]
df_female = df.iloc[136:247, :]
df_male.columns = df.iloc[249,:]
df_female.columns = df.iloc[135, :]

df_female.index = range(len(df_female))
df_male.index = range(len(df_male))

In [105]:
df_male.head()
df_male.tail()
df_female.head()
df_female.tail()



249  Year age x     m(x)     q(x)  a(x)    l(x) d(x)   L(x)     T(x)   e(x)
0    2015     0  0.00159  0.00159  0.15  100000  159  99864  7862257  78.62
1    2015     1  0.00013  0.00013   0.5   99841   13  99835  7762393  77.75
2    2015     2  0.00023  0.00023   0.5   99828   23  99816  7662558  76.76
3    2015     3    6e-05    6e-05   0.5   99805    6  99802  7562742  75.78
4    2015     4    6e-05    6e-05   0.5   99799    6  99795  7462940  74.78

249  Year age x     m(x)     q(x)  a(x) l(x) d(x) L(x) T(x)  e(x)
106  2015   106  0.69376  0.51508   0.5   21   11   16   30   1.4
107  2015   107  0.72263  0.53083   0.5   10    6    8   14  1.35
108  2015   108  0.74975  0.54532   0.5    5    3    4    6  1.31
109  2015   109  0.77506  0.55859   0.5    2    1    2    3  1.27
110  2015  110+  0.79849        1  1.25    1    1    1    1  1.25

135  Year age x     m(x)     q(x)  a(x)    l(x) d(x)   L(x)     T(x)   e(x)
0    2015     0  0.00178  0.00178  0.15  100000  178  99848  8419059  84.19
1    2015     1    4e-05    4e-05   0.5   99822    4  99821  8319211  83.34
2    2015     2    3e-05    3e-05   0.5   99819    3  99817  8219390  82.34
3    2015     3   0.0001   0.0001   0.5   99815   10  99810  8119573  81.35
4    2015     4    7e-05    7e-05   0.5   99805    7  99802  8019763  80.35

135  Year age x     m(x)     q(x)  a(x) l(x) d(x) L(x) T(x)  e(x)
106  2015   106   0.6878   0.5118   0.5   72   37   53  101   1.4
107  2015   107  0.72064  0.52976   0.5   35   19   26   47  1.35
108  2015   108  0.75127  0.54613   0.5   16    9   12   21   1.3
109  2015   109  0.77957  0.56093   0.5    7    4    5    9  1.26
110  2015  110+  0.80549        1  1.24    3    3    4    4  1.24

In [85]:
df_female.head()
df_female.tail()

Life Table Finland Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
136       2015       0    0.00178    0.00178    0.15  1          0        178   
137       2015       1      4e-05      4e-05        0.5      99822          4   
138       2015       2      3e-05      3e-05        0.5      99819          3   
139       2015       3     0.0001     0.0001        0.5      99815         10   
140       2015       4      7e-05      7e-05        0.5      99805          7   

    Unnamed: 7 Unnamed: 8 Unnamed: 9  
136      99848    8419059      84.19  
137      99821    8319211      83.34  
138      99817    8219390      82.34  
139      99810    8119573      81.35  
140      99802    8019763      80.35

Life Table Finland Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
243       2015     107    0.72064    0.52976        0.5         35         19   
244       2015     108    0.75127    0.54613        0.5         16          9   
245       2015     109    0.77957    0.56093        0.5          7          4   
246       2015    110+    0.80549          1       1.24          3          3   
247                NaN        NaN        NaN        NaN        NaN        NaN   

    Unnamed: 7 Unnamed: 8 Unnamed: 9  
243         26         47       1.35  
244         12         21        1.3  
245          5          9       1.26  
246          4          4       1.24  
247        NaN        NaN        NaN

In [19]:
age_s = 5
age_g = 55
rate = 0.02
l_g = df_fin.loc[age_g:, 'l(x)'].values / df_fin.loc[age_g, 'l(x)']

l_s = df_fin.loc[age_s: len(l_g) + 5 - 1, 'l(x)'].values / df_fin.loc[age_s, 'l(x)']

disc_factor = 1 / (1 + rate)
l_gs = l_g * l_s

print(len(l_g), len(l_s))

C = 0

k = 0
for val in l_gs:
    C += disc_factor ** k * val
    k += 1

C *= 500


r = 0.02

print("Exptected value of payments: ", np.round(C, decimals=4))


56 56
Exptected value of payments:  10789.1003


0.9803921568627451

## 10

find $(I - A)^{-1}m$

In [6]:
A = np.zeros([8,8])

low = np.arange(7)
A[low+1, low] = np.array([0.99, 0.97, 0.9, 0.8, 0.7, 0.5, 0.3])
A[0, :] = np.array([0, 0, 0.35, 0.5, 0.2, 0.05, 0, 0])

print('A =\n', A, '\n')
print('I - A =\n', np.eye(8) - A, '\n')

I = np.linalg.inv(np.eye(8) - A)
print('Inverse = \n',np.round(I, decimals=3), '\n')

m = 0.01 * np.ones([8,1])
print('m =\n', m, '\n')

Im = I.dot(m)
print('Answer =\n',Im)

A =
 [[0.   0.   0.35 0.5  0.2  0.05 0.   0.  ]
 [0.99 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.97 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.9  0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.8  0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.7  0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.5  0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.3  0.  ]] 

I - A =
 [[ 1.    0.   -0.35 -0.5  -0.2  -0.05  0.    0.  ]
 [-0.99  1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.   -0.97  1.    0.    0.    0.    0.    0.  ]
 [ 0.    0.   -0.9   1.    0.    0.    0.    0.  ]
 [ 0.    0.    0.   -0.8   1.    0.    0.    0.  ]
 [ 0.    0.    0.    0.   -0.7   1.    0.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.5   1.    0.  ]
 [ 0.    0.    0.    0.    0.    0.   -0.3   1.  ]] 

Inverse = 
 [[14.435 13.57  13.99   9.931  3.392  0.722  0.     0.   ]
 [14.29  14.435 13.85   9.832  3.358  0.715  0.     0.   ]
 [13.862 14.002 14.435  9.537  3.257  0.693 -0.    -0.   ]
 [12.476 12.602 12.991  9.583  2.932  0

In [13]:
np.round(I.dot(np.eye(8) - A), decimals=10)

array([[ 1.,  0.,  0.,  0.,  0., -0.,  0.,  0.],
       [-0.,  1.,  0., -0.,  0., -0.,  0.,  0.],
       [-0.,  0.,  1., -0.,  0., -0.,  0.,  0.],
       [-0.,  0.,  0.,  1.,  0., -0.,  0.,  0.],
       [ 0.,  0.,  0., -0.,  1., -0.,  0.,  0.],
       [-0.,  0.,  0., -0.,  0.,  1.,  0.,  0.],
       [-0.,  0.,  0., -0.,  0., -0.,  1.,  0.],
       [-0.,  0.,  0.,  0.,  0., -0.,  0.,  1.]])

In [25]:
n = np.ones([8,1])
np.linalg.matrix_power(A, 1).dot(n) + m

array([[1.11],
       [1.  ],
       [0.98],
       [0.91],
       [0.81],
       [0.71],
       [0.51],
       [0.31]])

In [20]:
l_g = df_fin.loc[55:, 'l(x)'].values / 10**5
l_s = df_fin.loc[5: len(l_g) + 4, 'l(x)'].values / 10**5

print(len(l_g), len(l_s))

r = 1 / (1 + 0.02)
l_gs = l_g * l_s

C = 0
k = 0

for val in l_gs:
    C += r ** k * val
    k += 1

C *= 500

print("Exptected value of payments: ", np.round(C, decimals=4))

56 56
Exptected value of payments:  10256.52


In [11]:
df_fin.head()

year age x     m(x)     q(x)  a(x)    l(x)  d(x)   L(x)     T(x)   e(x)
0  2015     0  0.00168  0.00168  0.15  100000   168  99856  8143956  81.44
1  2015     1  0.00009  0.00009  0.50   99832     9  99828  8044099  80.58
2  2015     2  0.00013  0.00013  0.50   99823    13  99817  7944272  79.58
3  2015     3  0.00008  0.00008  0.50   99810     8  99806  7844455  78.59
4  2015     4  0.00006  0.00006  0.50   99802     6  99799  7744649  77.60

In [12]:
df_fin.tail(5)

year age x     m(x)     q(x)  a(x)  l(x)  d(x)  L(x)  T(x)  e(x)
106  2015   106  0.68827  0.51205  0.50    50    26    38    71  1.40
107  2015   107  0.72078  0.52983  0.50    25    13    18    33  1.35
108  2015   108  0.75118  0.54608  0.50    12     6     8    15  1.30
109  2015   109  0.77932  0.56080  0.50     5     3     4     7  1.27
110  2015  110+  0.80513  1.00000  1.24     2     2     3     3  1.24

In [5]:
A = np.zeros([8,8])

low = np.arange(7)
A[low+1, low] = np.array([0.99, 0.97, 0.9, 0.8, 0.7, 0.5, 0.3])
A[0, :] = np.array([0, 0, 0.35, 0.5, 0.2, 0.05, 0, 0])

n = np.ones((8,1))

print(A.dot(n))
print(np.sum(A.dot(n)))

[[1.1 ]
 [0.99]
 [0.97]
 [0.9 ]
 [0.8 ]
 [0.7 ]
 [0.5 ]
 [0.3 ]]
6.26


In [6]:
ANW = A[:6, :6]
np.linalg.matrix_power(ANW, 9)

array([[0.17374984, 0.18837134, 0.25184872, 0.19016633, 0.06610619,
        0.0139848 ],
       [0.27689905, 0.17374984, 0.19225528, 0.16935063, 0.06226893,
        0.01437903],
       [0.2789532 , 0.27130513, 0.17374984, 0.09872667, 0.03099189,
        0.00658603],
       [0.11854857, 0.25359381, 0.25172641, 0.12764761, 0.03697465,
        0.0059757 ],
       [0.09561122, 0.09579683, 0.20914954, 0.18657467, 0.0678906 ,
        0.01493925],
       [0.20914954, 0.06760389, 0.06913173, 0.08133593, 0.03253437,
        0.00813359]])

Right eigenvector

In [60]:
eig_val, eig_vect = np.linalg.eig(A)
max_eigenvalue, i = np.max(np.abs(eig_val)), np.argmax(np.abs(eig_val))
print(max_eigenvalue.round(decimals=4), i)
print(eig_vect[:,i] / eig_vect[0,i])

0.9815 2
[1.        -0.j 1.00865913-0.j 0.99683984-0.j 0.9140651 -0.j
 0.74503443-0.j 0.53135358-0.j 0.27068416-0.j 0.08273577-0.j]


Left eigenvector

In [61]:
eig_val, eig_vect = np.linalg.eig(A.T)
max_eigenvalue, i = np.max(np.abs(eig_val)), np.argmax(np.abs(eig_val))
print(max_eigenvalue.round(decimals=4), i)
print(eig_vect[:,i] / eig_vect[0,i])

0.9815 0
[ 1.        -0.j  0.99141521-0.j  1.00317018-0.j  0.7051251 -0.j
  0.24010129-0.j  0.05094238-0.j -0.        -0.j -0.        -0.j]


Since $\lambda < 1, A^t n$ goes to zero as t goes to infinity

In [64]:
np.linalg.matrix_power(A, 40000).dot(np.ones(8))

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
w = np.array([1, 1.0087, 0.9968, 0.9141, 0.7450, 0.5314, 0.2707, 0.0827])
w3 = A.dot(w)
w3

array([0.9815  , 0.99    , 0.978439, 0.89712 , 0.73128 , 0.5215  ,
       0.2657  , 0.08121 ])

In [82]:
m = 0.01 * np.ones(8).reshape(-1,1)
m

array([[0.01],
       [0.01],
       [0.01],
       [0.01],
       [0.01],
       [0.01],
       [0.01],
       [0.01]])

array([[0.56040397],
       [0.56479993],
       [0.55785593],
       [0.51207034],
       [0.41965627],
       [0.30375939],
       [0.16187969],
       [0.05856391]])